[package]
name = "ndarray-rand"
version = "0.1.0"
authors = ["bluss"]
license = "MIT/Apache-2.0"

repository = "https://github.com/bluss/rust-ndarray"
documentation = "http://bluss.github.io/rust-ndarray/"

description = "Constructors for randomized arrays. `rand` integration for `ndarray`."

keywords = ["multidimensional", "matrix", "rand", "ndarray"]

[dependencies]
rand = "0.3"
ndarray = { version = ">= 0.4.4, <= 0.5.0-alpha.10", path = ".." }
